### ISSUE TITLE
GasBuddy with Firebase - Fire Hazard

### ISSUE THREAD

**Issue by pfflanders** [yliu1021/GasBuddy#1]
As the title implies, I am concerned about the use of Firebase with this 'GasBuddy'. Potentially very dangerous to users of this product. 
I suggest developers to consider using [Firehose](http://firehose.io/) as a safety backup or switching all together to a storage method which is compliant with OSHA's Title 29 Code of Federal Regulations: [29 CFR 1926.152](https://www.govinfo.gov/app/details/CFR-2010-title29-vol8/CFR-2010-title29-vol8-sec1926-152).

**Comment by yliu1021** [comment]
Ack
